require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false
$RNFirebaseAsStaticFramework = true
# pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
# pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false

target 'MyApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  # use_modular_headers!
  use_frameworks! :linkage => :static
  # $static_framework = true 
  # Add the project and build configurations
  # project 'MyApp',
  #   'Dev.Debug' => :debug, # '{Build Configuration name}' => :{debug or release}
  #   'Debug' => :debug,
  #   'Dev.Release' => :release,
  #   'Release' => :release

  # $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  #    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
  #    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  #    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
  #  pre_install do |installer|
  #    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  #    installer.pod_targets.each do |pod|
  #        if $static_framework.include?(pod.name)
  #          def pod.build_type;
  #            Pod::BuildType.static_library
  #          end
  #        end
  #      end
  # end

  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNPurchases')
  #       def pod.build_type;
  #       Pod::BuildType.static_library # pods version >= 1.9
  #      end
  #     end
  #   end
  # end

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
  #     end
  #   end
  # end
end
